### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Alpha-Flyte** [quat1024/apathy#10]
So this was initially what I believed to be an issue with one of MehVahdJukaar's mods (Supplementaries, Moonlight Lib, Every Compat)
https://github.com/MehVahdJukaar/WoodGood/issues/13#issuecomment-1181816981

However, upon closer inspection of the crash log, it appears Apathy was causing my client to crash on startup instead. It may be a compat issue between one of the above mods and Apathy, but when Apathy was removed, the crash was resolved and Minecraft proceeded to the home screen.

I have no idea why Apathy is causing the startup error, since it features in Vazkii's Bliss modpack, which I took much inspiration from when crafting my own personal use pack, and which uses the mods mentioned above.

Please look into this, as Apathy is quite a gameplay-changing mod, which I would hate to see gone from my personal use pack.

As for details, see below:
MC Version 1.18.2
Forge Version 40.1.14
Mods: Quite a bunch (199 mods excluding Apathy), most major ones include Create, Quark, the mods listed above, several mods by Serilum, Biomes O' Plenty, Farmer's Delight, Immersive Weathering, just to name a few

**Comment by quat1024** [comment]
What on earth??? there's no way this should be possible lol

**Comment by quat1024** [comment]
sorry im gonna be busy for a few days but i really want to investigate what the heck this is

**Comment by quat1024** [comment]
Oops its been a few months

Apathy (on forge) used to initialize itself way too early which caused other issues as well, but the newer versions wait until world load time to initialize rules instead of doing it before other mods are able to init. This should be fixed ?

**Comment by quat1024** [comment]
Haven't heard back, gonna assume this has been fixed
