### ISSUE TITLE
Question/Suggestion 

### ISSUE THREAD

**Issue by SilveroGhost** [quat1024/apathy#17]
Hello, I was linked to this mod by another modder for my question/suggestion,
would it be possible to make some sort of list or way to pick and choose which mobs are hostile towards individual players using their specific IGNs or User Id's? So that way one player can walk through a horde of zombies while others are attacked by them?
Or if there's a way to already do something like that, how would I do so within this mod?
Thank you for reading my ramble, and regardless of the answer thank you for making this mod :>

**Comment by quat1024** [comment]
You can probably worm your way into that with the "player set" stuff, but I will freely admit that it should be a million times easier to set up

**Comment by SilveroGhost** [comment]
> You can probably worm your way into that with the "player set" stuff, but I will freely admit that it should be a million times easier to set up

oh, thats awesome! So, if you like the idea and would want to maybe add a feature like that to your mod I feel that would be a fantastic addition (and a life saver to me and other players that are desperate for a feature like that) but if not I'll do my best to work with the current mod, thank you for the reply!
