### ISSUE TITLE
Add Scoreboard predicate in mob.json ?

### ISSUE THREAD

**Issue by Bluberry-Kat** [quat1024/apathy#2]
This is kind of a huge disaster and I don't know how possible it is  
The conceptual use-case is something like Runescape, where certain mobs target you by default, but stop being hostile outright if you're a good deal stronger than them.  
For this case I (as a pack developer) would manually track a player's "strength" via some kind of heuristic inside a Scoreboard, and deny the mob's aggression if said scoreboard passes a certain comparison (probably a json object for common arithmetic comparisons, like less-than, greater-than, etc)  
That's just for the specific use-case I have in mind; datapacks are scary and I'm sure someone will figure out more things it could be used for

**Comment by quat1024** [comment]
Neat idea. Added this in 2.0 which is on curse and modrinth right now. [Documentation here](https://github.com/quat1024/apathy/blob/trunk/docs/1.16-1.18/JSON.md#apathyscore--new-in-118-).
