### ISSUE TITLE
[bug] Changing the initial end gateway count causes the ender dragon and exit portal to just not exist

### ISSUE THREAD

**Issue by spacialflaw** [quat1024/apathy#21]
Can be replicated by just changing the end gateway count (I had it on 3) and loading a new end dimension. 

The version of the mod is 2.7 Forge 1.19.2

**Comment by quat1024** [comment]
Well huh, that's weird. Missed this in my testing because I typically test all the config options at once, and if you set `portalInitialState` to not-`closed` it turns up.

**Comment by quat1024** [comment]
Also affects the 1.20 builds (notable cause i rewrote some of the End stuff cause mojang)

**Comment by quat1024** [comment]
(a workaround, to fix any extant broken Ends: cheat in an End Crystal and place it on a block of obsidian, it will spawn an End Portal. vanilla mechanic)

**Comment by quat1024** [comment]
Ok, this should be fixed in `2.7.1` available in [the usual places](https://modrinth.com/mod/apathy/versions).
